FROM node:20-alpine AS builder
WORKDIR /app
COPY spotify-auth-express-master/package.json ./
RUN npm cache clean --force
RUN npm install --production --legacy-peer-deps --force
COPY spotify-auth-express-master/ ./
EXPOSE 2223
CMD ["node", "start.js"]
